name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4

      -
        name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - 
        uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: latest
          run_install: false

      -
        name: Install and Build
        run: |
          pnpm install
          pnpm build

      -
        name: Deploy Tserver
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.T_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.T_KEY }}
          port: ${{ secrets.PORT }}
          rm: true
          source: "build/"
          strip_components: 1
          target: "/var/www/html"

      -
        name: Deploy Oserver
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.O_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.O_KEY }}
          port: ${{ secrets.PORT }}
          rm: true
          source: "build/"
          strip_components: 1
          target: "/var/www/html"